### ISSUE TITLE
Ref Finance AMM UI | Bounty $TBD

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#44]
# Description
User interface for AMM in Ref Finance

## Context

Contracts: https://github.com/ref-finance/ref-contracts

Specifically, ref-exchange is AMM contract.

TODO: functioning version on testnet

Important note, the method in near-api-js to sign transactions with Wallet supports a list of transactions which can be going to different receivers. This allows to batch in one round trip to the Wallet signing a sequence like storage_deposit + ft_transfer_call.

# Acceptance Criteria

<img width="564" alt="Screen Shot 2021-03-10 at 5 38 35 AM" src="https://user-images.githubusercontent.com/175486/110638021-e7c29800-8162-11eb-86e0-3088a542051a.png">

Repo for UI: https://github.com/ref-finance/ref-ui

Please make pull request to this repo (you can delete all files there).

* [ ] [Sushi Swap](https://app.sushi.com) like UI for interacting with various functionality of the pool
* [ ] Portfolio page, shows how much assets are deposited into the Ref Finance contract and are ready for trading. There is deposit and withdraw, where user can enter token (either from dropdown of supported tokens or by typing account id of the new token). Deposit will ft_transfer_call it with receiver to be Ref contract (should check from frontend first that Ref contract is registered for storage with this fungible token, and if it is not - add storage_deposit call), and withdraw button will call `withdraw` method.
* [ ] Swap page is the usual selecting token from and to token. Show how much would one receive if they do this exchange. Note, that `swap` method takes (a) set of swap actions via pool (b) only acts on deposits in the portfolio. Which means that user first needs to deposit funds in Portfolio page to trade - lead them back to deposit if they don't have selected funds. 
     * [ ] To start let's use simple matching algorithm: 
            1. get list of current pools that contract has 
            2. check which ones are servicing the pair that user wants
            3. fetch from each one what will be the outcome amount
            4. select best one
* [ ] Liquidity page, shows all the pools available sorted by amount of liquidity in them. Allow to click "Provide liquidity" on these pools if user has the respected tokens in portfolio (if not - send them to deposit the tokens).
     * [ ]  For each pool show if user already provided liquidity by showing % of the pool shares they own?
* [ ] On the top there should be a banner that contracts are not security reviewed yet and all risks are on the user.
* [ ] The UI implementation should be done in the way that it's easy to add other options in the menu and new pages with other logic.

# Bounty
[Amount paid in NEAR]

# Process

Please comment prospective cost & time it will take for you to implement.
Ideally split your proposal into smaller milestones with increasing refinement of the interface

**Comment by rauchp** [comment]
Taking a look at this now! Will circle back with any questions once I've taken a good look.

**Comment by lau-bin** [comment]
Hello, i want to do this bounty.
Im fullstack with rust and react, this is one of the frontends i already made for NEAR: 
https://www.narwallets.com/dapp/testnet/usdnear/
https://devfolio.co/submissions/usdn-b42e
For an mvp i estimate 2 weeks.

**Comment by rauchp** [comment]
Got started on this last night + started some wiring. I need to look more into the contracts and the whole scope of the project before providing a more precise proposal. Hoping to write that out tomorrow. As of now I see an MVP possible in 10 days, but need to doublecheck and scope it out a bit more.

<img width="850" alt="ref screenshot" src="https://user-images.githubusercontent.com/22400533/110848509-6b67ac00-826b-11eb-8446-e328d4f25348.png">

As a side note, I feel like Ref is missing a cool logo like Sushi's in order to give it more flavor 👀

**Comment by JPiao** [comment]
@rauchp damn, just that is looking pretty slick 👀 looks like you got it down. Looking forward to the final product

**Comment by aidai524** [comment]
Hi @ilblackdragon , I review your contracts code yesterday, there can do sushi like dapp, I list the details for todo list:

**Comment by aidai524** [comment]
Hi @ilblackdragon, please let me know if the opportunity is still open.
I reviewed your contracts code yesterday,  believe that I deliver do SUSHI like frontend part dapp in aggregate of 11days

here is an outline of the todo lists and time required for each item.

1. UI Works: 2D

2. Portfolio page and wallet connect: 2D
    * Sign in with NEAR
    * Assets State View
    * Deposit & Withdraw functions 

    
3. Swap page: 3D
    * Fetch pools list and token pairs
    * Select pairs and swap

    
4. Liquidity page: 2D
    * Fetch pools list
    * Show user's % share in a pool

    
5. Test and fix bugs: 2D

And I think during the development process, we need discuss the details of contract interaction.
open to collborative work too, since i see a couple of people proposed intention to work on this too.
please let me know if still needed.

**Comment by ilblackdragon** [comment]
Thanks for starting @rauchp, looks good.

@aidai524, @JPiao, @lau-bau thanks for the interest.

If you all join this TG channel - we can all discuss in more realtime how to collaborate on this and discuss the smart contract: https://t.me/ref_finance

**Comment by ilblackdragon** [comment]
Closing, bounty is finished at this point.
