### ISSUE TITLE
Implement community coin for discussion sites, forums and social platforms | Bounty: 2500 NEAR

### ISSUE THREAD

**Issue by behaviary** [near/bounties#7]
# Description
Implement a basic fungible token with an extension for minting that can be used in any online community that wishes to engage moderators, content creators and community memebers* 

## Context:

- NEAR has NEP-21 standard for Fungible Token.
- Reddit recently created community points for some of their subreddits (https://www.reddit.com/community-points/)
- Other communities (such as dev.to) would benefit from a similar point system

## Flow/experiences

1. Receive coins for participating in a community 
1. View that you've been sent some coins for participation
1. Send coins to other users on the platform

# Acceptance
* [ ] Contract for fungible token with minting
* [ ] Sdk/library for integrating the coin into a community platform
* [ ]  Example UI where the coin is integrated with a community

# Bounty
## 2500 Ⓝ

**(typo was on purpose. Get it? meme-bers. Like memes. get it? You get it)*

**Comment by sarangparikh22** [comment]
@potatodepaulo This looks like a very interesting Bounty. Especially with the traction gained by the Reddit with their Community Token. Before approaching this, I have few points of discussion. 

1) Should we make it like a Factory Contract type of Mechanism where you have a website where anyone can come deploy the Token for their website and we will give them appropriate API (Generalized)  or Is it like, we specifically fine tune contract for every website (Customized).

2) How do we manage to onboard the First-Time users as they wouldn't be having any NEAR. Possibly we can have a meta-transaction for them.

Maybe I can just start with the Acceptance Criteria mentioned and we can iterate over it later on. 

Let me know what you think.

**Comment by behaviary** [comment]
@sarangparikh22 Good thoughts. Sorry it took me so long to respond to this.

1. That's up to the creator of the contract. The factory contract makes much more sense in the long term. In the short term though, I personally would be happy to see any basic working example. Since it's blockchain, you could get around permission/API by building the very first UI as a chrome extension that overlays UI onto any community. This also allows cross-platform points, which is killer.
2. AFA onboarding first time users: it would need to be on a TestNet contract. You would probably need to get a community/sub-commmunity to buy into what you're trying to do. Do you have any online communities you're a part of?

**Comment by vgrichina** [comment]
@sarangparikh22 @potatodepaulo somewhat related subreddit for inspiration https://www.reddit.com/r/MemeEconomy/

**Comment by thyamarkos** [comment]
@potatodepaulo We (DigitalMOB) are actually thinking of implementing this as a standalone application with local registration, wallet generation on registration and sort of a reward or bounty system from the user starting a new thread to users contributing valuable answers. Since this will have a ReactJS frontend and a JSON-RPC backend API on the server side, this could also later be turned into an SDK (JavaScript, TypeScript...) to integrate in other websites (SSO with Google or GitHub account, get your wallet and you're off to the races).
The integration of the coin would be developed as a separate library, so it would allow the contract and coin itself to be integrated into similar platforms.
